dataset_params:
  train_directory: [
    ]
  test_directory: [
    images/obama/video0,   
    images/obama/video1,
    images/obama/video2,
    images/obama/video3,
    images/obama/video4,
    ]
  H: 512
  W: 512
  focal: 

model_params:
  num_blendshapes: 50
  decoder:
    num_blocksperscale : 1
    num_layers: 4
    max_features: 1024
    scale_factor : 2
    num_blocks : 2
    fhidden : 128
    num_resblocks : 0
  num_basis: 19  # 4x(16+3)
  scale_factor: 2
  superimpose: 4
  discriminator:
    num_blocks: 5
    max_features: 512
    sn: True

test_params:
  batch_size: 1
